project:
  name: akiya-lens
  role: "etl"
  version: v1
  description: "住宅・空き家（2018/2023）整形と現況指標の作成"

io:
  raw_dir: data/raw
  processed_dir: data/processed
  encoding_in_candidates: ["utf-8-sig","utf-8","cp932","shift_jis"]
  encoding_out: utf-8-sig

datasets:
  # 空き家率
  housing_vacancy:
    sources:
      "2018": "FEH_00200522_2018_2508.csv"
      "2023": "FEH_00200522_2023_2508.csv"
    columns_map:
      市区町村コード: ["地域 コード","標準地域コード","全国地方公共団体コード"]
      市区町村名: ["地域","市区町村","団体名"]
      総数: ["総数","住宅総数"]
      空き家: ["空き家","空家"]
    dtypes:
      市区町村コード: "str"
      市区町村名: "str"
      総数: "float"
      空き家: "float"
    output:
      filename_template: "housing_vacancy__wide__${project.version}__${date:%Y%m%d}.csv"
  # 人口動態
  population_stats:
    columns_map:
      市区町村コード: ["地域 コード","標準地域コード"]
      市区町村名: ["地域","市区町村"]
      year_raw: ["調査年"]
      総人口: ["A1101_総人口【人】"]
      15歳未満人口: ["A1301_15歳未満人口【人】"]
      15〜64歳人口: ["A1302_15〜64歳人口【人】"]
      65歳以上人口: ["A1303_65歳以上人口【人】"]
      出生数: ["A4101_出生数【人】"]
      死亡数: ["A4200_死亡数【人】"]
      転入者数: ["A5103_転入者数【人】"]
      転出者数: ["A5104_転出者数【人】"]
      世帯数: ["A7101_世帯数【世帯】"]
  # 地価公示
  landprice_ksj_l01:
    # 年ごとのソース（必要なら明示。県ごと複数XMLならglobで指定）
    sources:
      "2018": "data/raw/landprice/2018/L01-*.xml"
      "2023": "data/raw/landprice/2023/L01-*.xml"

    # KSJ L01 既定の名前空間（変更時はここだけ直せばOK）
    namespaces:
      app: "http://nlftp.mlit.go.jp/ksj/schemas/ksj-app"
      gml: "http://schemas.opengis.net/gml/3.2.1/gml.xsd"
      xlink: "http://www.w3.org/1999/xlink"

    # 1レコード（標準地点）のルート
    item_xpath: ".//app:LandPrice"

    # 列名統一（日本語）と、そのXPath定義
    fields:
      year: "app:year/gml:TimeInstant/gml:timePosition"
      市区町村コード: "app:administrativeAreaCode"
      市区町村名: "app:cityName"
      価格_円m2: "app:postedLandPrice"
      利用現況: "app:currentUse"
      座標_pos: "app:position/gml:Point/gml:pos"

    # 出力ファイル（テンプレ）
    output:
      points_template: "landprice_points__${project.version}__${date:%Y%m%d}.csv"
      long_template: "landprice_residential_median__long__${project.version}__${date:%Y%m%d}.csv"
      wide_template: "landprice_residential_median__wide__${project.version}__${date:%Y%m%d}.csv"


# 学習対象エリア(都道府県コード)
study_regions:
  yatsugatake_alps:
    prefecture_codes: ["19","20","21","22"]
  yatsugatake_core:
    prefecture_codes: ["19","20"]
  all:
    prefecture_codes: []

join:
  city_master_path: data/master/city_master__all__v1__preview.csv

validation:
  housing_vacancy:
    required: ["市区町村コード","市区町村名","総数","空き家","year"]
    rules:
      市区町村コード: {type: str, pattern: "^[0-9]{5}$"}
      year: {type: int, allowed: [2018, 2023]}
logging:
  level: INFO
